version: '3.1'
services:

  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - manage-recalls-ui
    container_name: redis 
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - manage-recalls-ui
    container_name: hmpps-auth
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DELIUS_ENABLED=false

  fake-manage-recalls-api:
    build: ./fake-manage-recalls-api
    networks:
      - manage-recalls-ui
    container_name: fake-manage-recalls-api
    ports:
      - "9091:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/liveness" ]
    command: --verbose

  fake-prison-register-api:
    image: quay.io/hmpps/ppud-fake-prison-register-api:latest
    networks:
      - manage-recalls-ui
    container_name: fake-prison-register-api-e2e
    ports:
      - "9094:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    command: --verbose

  manage-recalls-ui:
    build: .
    networks:
      - manage-recalls-ui
    container_name: manage-recalls-ui
    depends_on: [redis, fake-manage-recalls-api, fake-prison-register-api]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev
      - REDIS_HOST=redis
      - INGRESS_URL=http://localhost:3000
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - MANAGE_RECALLS_API_URL=http://fake-manage-recalls-api:8080
      - PRISON_REGISTER_API_URL=http://fake-prison-register-api:8080
      - API_CLIENT_ID=ppud-ui-client
      - API_CLIENT_SECRET=clientsecret
      - SYSTEM_CLIENT_ID=system-client-id
      - SYSTEM_CLIENT_SECRET=system-client-secret
      - SESSION_SECRET=session-secret

networks:
  manage-recalls-ui:
