version: '3.1'
services:

  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - manage-recalls-ui
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  wiremock:
    image: rodolpheche/wiremock
    networks:
      - manage-recalls-ui
    depends_on: [redis]
    ports:
      - "9999:8080"
    restart: always
    command: --verbose

#  app:
#    build: .
#    networks:
#      - manage-recalls-ui
#    depends_on: [redis, hmpps-auth, mockserver]
#    depends_on: [redis]
#    ports:
#      - "3000:3000"
#    environment:
#      - REDIS_HOST=redis
#      - INGRESS_URL=http://localhost:3000
#      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
#      - HMPPS_AUTH_URL=http://localhost:9090/auth
#      - TOKEN_VERIFICATION_API_URL=http://localhost:9090/verification
#      - API_CLIENT_ID=ppud-ui-client
#      - API_CLIENT_SECRET=clientsecret
#      - SYSTEM_CLIENT_ID=NA
#      - SYSTEM_CLIENT_SECRET=NA
#      - SESSION_SECRET=secret

networks:
  manage-recalls-ui:
