/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { AddDocumentRequest } from './models/AddDocumentRequest'
export type { AddDocumentResponse } from './models/AddDocumentResponse'
export { ApiRecallDocument } from './models/ApiRecallDocument'
export type { BookRecallRequest } from './models/BookRecallRequest'
export { GetDocumentResponse } from './models/GetDocumentResponse'
export { ModelAndView } from './models/ModelAndView'
export type { Mono_ResponseEntity_List_SearchResult_ } from './models/Mono_ResponseEntity_List_SearchResult_'
export type { Mono_ResponseEntity_Pdf_ } from './models/Mono_ResponseEntity_Pdf_'
export type { Pdf } from './models/Pdf'
export { RecallResponse } from './models/RecallResponse'
export type { SearchRequest } from './models/SearchRequest'
export type { SearchResult } from './models/SearchResult'
export type { SentenceLength } from './models/SentenceLength'
export type { SentenceLengthReq } from './models/SentenceLengthReq'
export type { SentenceLengthRes } from './models/SentenceLengthRes'
export { UpdateRecallRequest } from './models/UpdateRecallRequest'
export type { View } from './models/View'
