import { getFormValues } from './getFormValues'
import { FormError, ObjectMap, DecoratedRecall } from '../../@types'
import { RecallResponse } from '../../@types/manage-recalls-api/models/RecallResponse'
import { RecallDocument } from '../../@types/manage-recalls-api/models/RecallDocument'
import updateRecallResponse from '../../../fake-manage-recalls-api/stubs/__files/get-recall.json'
import { decorateDocs } from '../documents/download/helpers/decorateDocs'
import { ConfirmedRecallTypeRequest } from '../../@types/manage-recalls-api/models/ConfirmedRecallTypeRequest'

describe('getFormValues', () => {
  const errors = {
    inCustodyAtBooking: {
      text: 'Custody status',
    },
    inCustodyAtAssessment: {
      text: 'Custody status',
    },
    recommendedRecallType: {
      text: 'Recommended recall type',
    },
    confirmedRecallType: {
      text: 'Confirmed recall type',
    },
    confirmedRecallTypeDetail: {
      text: 'Confirmed recall type detail',
    },
    recallEmailReceivedDateTime: { values: { year: '', month: '12', day: '05', hour: '15', minute: '33' } },
    lastReleasePrison: {
      text: 'Releasing prison',
    },
    sentenceDate: { values: { year: '2020', month: '', day: '05' } },
    sentenceExpiryDate: { values: { year: '', month: '', day: '' } },
    licenceExpiryDate: { values: { year: '', month: '', day: '05' } },
    conditionalReleaseDate: { values: { year: '', month: '12', day: '05' } },
    lastReleaseDate: { values: { year: 'www', month: 'rr', day: 'ee' } },
    localPoliceForceId: {
      text: 'Local police force',
    },
    sentencingCourt: {
      text: 'Sentencing court',
    },
    indexOffence: {
      text: 'Index offence',
    },
    contraband: {
      text: 'Contraband',
    },
    contrabandDetail: {
      text: 'Contraband detail',
    },
    vulnerabilityDiversity: {
      text: 'Vulnerability',
    },
    vulnerabilityDiversityDetail: {
      text: 'Vulnerability detail',
    },
    arrestIssues: {
      text: 'Arrest issues',
    },
    arrestIssuesDetail: {
      text: 'Vulnerability detail',
    },
    mappaLevel: {
      text: 'MAPPA level',
    },
    sentenceLength: {
      values: {
        days: '',
        months: 'rr',
        years: '',
      },
    },
    bookingNumber: {
      text: 'Booking number',
    },
    probationOfficerName: {
      text: 'Probation officer',
    },
    probationOfficerPhoneNumber: {
      text: 'Phone',
      values: '999',
    },
    probationOfficerEmail: {
      text: 'Email',
      values: 'invalid@email',
    },
    localDeliveryUnit: {
      text: 'Local Delivery Unit',
    },
    authorisingAssistantChiefOfficer: {
      text: 'ACO',
    },
    licenceConditionsBreached: {
      text: 'Breached licence conditions',
    },
    reasonsForRecall: {
      text: 'Reasons for recall',
    },
    reasonsForRecallOtherDetail: {
      text: 'Other detail',
    },
    currentPrison: {
      text: 'Current prison',
    },
    recallNotificationEmailFileName: {
      text: 'An error occurred uploading the email',
      values: 'email.msg',
    },
    dossierEmailFileName: {
      text: 'An error occurred uploading the email',
      values: 'dossier.msg',
    },
    rescindRequestDetail: {
      text: 'Rescind request detail',
    },
    recallNotificationEmailSentDateTime: { values: { year: '', month: '', day: '05', hour: '05', minute: '3' } },
    rescindRequestEmailReceivedDate: { values: { year: '', month: '43', day: '' } },
    dossierEmailSentDate: { values: { year: '2016', month: '', day: '13' } },
    confirmRecallNotificationEmailSent: { text: 'Recall notification email sent' },
    confirmDossierEmailSent: { text: 'Dossier email sent' },
    previousConvictionMainNameCategory: { text: 'What is the main name on the pre-cons?' },
    licenceNameCategory: { text: 'What is the licence name?' },
    previousConvictionMainName: { text: 'What is the other main name used?' },
    hasDossierBeenChecked: { text: 'Has the dossier been checked for accuracy?' },
    warrantReferenceNumber: { text: 'Warrant reference number' },
    returnedToCustodyDateTime: { values: { year: '', month: '', day: '05', hour: '05', minute: '3' } },
    returnedToCustodyNotificationDateTime: { values: { year: '', month: '', day: '05', hour: '05', minute: '3' } },
    missingDocumentsDetail: {
      text: 'Missing documents detail',
    },
    subject: {
      text: 'Notes subject',
    },
    details: {
      text: 'Notes detail',
    },
    partBReceivedDate: { values: { year: '2016', month: '', day: '13' } },
    partBDetails: {
      text: 'Part B detail',
    },
    rereleaseSupported: {
      text: 'Re-release supported',
    },
    legalRepresentativeInfo_fullName: {
      text: 'Legal rep name',
    },
    legalRepresentativeInfo_email: {
      text: 'Legal rep email',
      values: 'invalidemail.com',
    },
    legalRepresentativeInfo_phoneNumber: {
      text: 'Legal rep phone',
      values: '999',
    },
    seniorProbationOfficerInfo_fullName: {
      text: 'Senior probation officer name',
    },
    seniorProbationOfficerInfo_email: {
      text: 'Senior probation officer email',
      values: 'invalidemail.com',
    },
    seniorProbationOfficerInfo_phoneNumber: {
      text: 'Senior probation officer phone',
      values: '999',
    },
    seniorProbationOfficerInfo_functionalEmail: {
      text: 'Probation functional email address',
      values: '',
    },
  } as unknown as ObjectMap<FormError>

  const unsavedValues = {
    inCustodyAtBooking: 'NO',
    inCustodyAtAssessment: 'YES',
    confirmedRecallType: 'NO',
    confirmedRecallTypeDetail: 'Reasons for no...',
    recommendedRecallType: 'STANDARD',
    recallEmailReceivedDateTimeParts: { year: '2020', month: '12', day: '05', hour: '15', minute: '33' },
    sentenceDateParts: { year: '2020', month: '12', day: '05' },
    sentenceExpiryDateParts: { year: '2020', month: '12', day: '05' },
    licenceExpiryDateParts: { year: '2020', month: '12', day: '05' },
    lastReleaseDateParts: { year: '2020', month: '12', day: '05' },
    conditionalReleaseDateParts: { year: '2020', month: '12', day: '05' },
    sentenceLengthParts: {
      days: '',
      months: '3',
      years: '',
    },
    lastReleasePrison: 'Portland',
    localPoliceForceId: 'dyfed-powys',
    sentencingCourt: 'Dorchester',
    indexOffence: 'Assault',
    contraband: 'YES',
    contrabandDetail: 'Likelihood of smuggling knives',
    vulnerabilityDiversity: 'NO',
    vulnerabilityDiversityDetail: '',
    arrestIssues: 'YES',
    arrestIssuesDetail: 'Detail..',
    mappaLevel: 'LEVEL_2',
    missingDocumentsDetail: 'Detail..',
    bookingNumber: '87378435D',
    probationOfficerName: 'Andy Fleming',
    probationOfficerPhoneNumber: '0739738383',
    probationOfficerEmail: 'andy@probation.gov.uk',
    localDeliveryUnit: 'ISLE_OF_MAN',
    authorisingAssistantChiefOfficer: 'Carrie Grant',
    licenceConditionsBreached: '(iii) three \n (iv) four',
    reasonsForRecall: ['POOR_BEHAVIOUR_NON_COMPLIANCE'],
    reasonsForRecallOtherDetail: '',
    currentPrison: 'ACL',
    recallNotificationEmailFileName: 'recall.msg',
    recallNotificationEmailSentDateTimeParts: { year: '2019', month: '04', day: '23', hour: '6', minute: '34' },
    rescindRequestEmailReceivedDateParts: { year: '2019', month: '04', day: '23', hour: '6', minute: '34' },
    dossierEmailFileName: 'dossier.msg',
    dossierEmailSentDateParts: { year: '2020', month: '11', day: '17' },
    confirmRecallNotificationEmailSent: 'YES',
    confirmDossierEmailSent: 'YES',
    previousConvictionMainNameCategory: 'FIRST_LAST',
    licenceNameCategory: 'FIRST_LAST',
    previousConvictionMainName: 'Wayne Holt',
    hasDossierBeenChecked: 'YES',
    rescindRequestDetail: 'Detail...',
    warrantReferenceNumber: '02RC/1234567C12345',
    returnedToCustodyDateTimeParts: { values: { year: '2021', month: '12', day: '05', hour: '05', minute: '3' } },
    returnedToCustodyNotificationDateTimeParts: {
      values: { year: '2021', month: '12', day: '05', hour: '05', minute: '2' },
    },
    subject: 'Subject for note',
    details: 'Detail for note...',
    partBReceivedDateParts: { values: { year: '2016', month: '', day: '13' } },
    partBDetails: 'Part B detail',
    rereleaseSupported: 'NO',
    legalRepresentativeInfo_fullName: 'Jenny Edwards',
    legalRepresentativeInfo_email: 'jenny@edwards.com',
    legalRepresentativeInfo_phoneNumber: '07484839483',
    seniorProbationOfficerInfo_fullName: 'Jimi Matthews',
    seniorProbationOfficerInfo_email: 'jim@probation.com',
    seniorProbationOfficerInfo_phoneNumber: '07434534583',
    seniorProbationOfficerInfo_functionalEmail: 'unsaved@probation.com',
  }

  const apiValues = {
    ...updateRecallResponse,
    ...decorateDocs({
      docs: updateRecallResponse.documents as RecallDocument[],
      recall: {
        nomsNumber: '123',
        recallId: '456',
        bookingNumber: updateRecallResponse.bookingNumber,
        firstName: 'Bobby',
        lastName: 'Badger',
      } as RecallResponse,
    }),
    enableDeleteDocuments: false,
  }
  it('uses errors if no unsaved or API values', () => {
    const formValues = getFormValues({ errors, unsavedValues: {}, apiValues: {} as DecoratedRecall })
    expect(formValues).toEqual({
      confirmedRecallType: '',
      arrestIssues: '',
      arrestIssuesDetail: '',
      authorisingAssistantChiefOfficer: '',
      bookingNumber: '',
      conditionalReleaseDateParts: {
        day: '05',
        month: '12',
        year: '',
      },
      confirmDossierEmailSent: '',
      confirmRecallNotificationEmailSent: '',
      contraband: '',
      contrabandDetail: '',
      currentPrison: '',
      details: '',
      dossierEmailSentDateParts: {
        day: '13',
        month: '',
        year: '2016',
      },
      inCustodyAtBooking: '',
      inCustodyAtAssessment: '',
      hasDossierBeenChecked: '',
      previousConvictionMainNameCategory: '',
      licenceNameCategory: '',
      indexOffence: '',
      lastReleaseDateParts: {
        day: 'ee',
        month: 'rr',
        year: 'www',
      },
      lastReleasePrison: '',
      legalRepresentativeInfo_fullName: '',
      legalRepresentativeInfo_email: 'invalidemail.com',
      legalRepresentativeInfo_phoneNumber: '999',
      licenceConditionsBreached: '',
      licenceExpiryDateParts: {
        day: '05',
        month: '',
        year: '',
      },
      localPoliceForceId: '',
      mappaLevel: '',
      missingDocumentsDetail: '',
      partBDetails: '',
      previousConvictionMainName: '',
      localDeliveryUnit: '',
      probationOfficerEmail: 'invalid@email',
      probationOfficerName: '',
      probationOfficerPhoneNumber: '999',
      reasonsForRecall: '',
      reasonsForRecallOtherDetail: '',
      recallEmailReceivedDateTimeParts: {
        day: '05',
        hour: '15',
        minute: '33',
        month: '12',
        year: '',
      },
      recallNotificationEmailSentDateTimeParts: {
        day: '05',
        hour: '05',
        minute: '3',
        month: '',
        year: '',
      },
      recommendedRecallType: '',
      rereleaseSupported: '',
      rescindRequestDetail: '',
      rescindRequestEmailReceivedDateParts: {
        day: '',
        month: '43',
        year: '',
      },
      returnedToCustodyDateTimeParts: {
        day: '05',
        hour: '05',
        minute: '3',
        month: '',
        year: '',
      },
      returnedToCustodyNotificationDateTimeParts: {
        day: '05',
        hour: '05',
        minute: '3',
        month: '',
        year: '',
      },
      seniorProbationOfficerInfo_email: 'invalidemail.com',
      seniorProbationOfficerInfo_fullName: '',
      seniorProbationOfficerInfo_phoneNumber: '999',
      seniorProbationOfficerInfo_functionalEmail: '',
      sentenceDateParts: {
        day: '05',
        month: '',
        year: '2020',
      },
      sentenceExpiryDateParts: {
        day: '',
        month: '',
        year: '',
      },
      sentenceLengthParts: {
        days: '',
        months: 'rr',
        years: '',
      },
      sentencingCourt: '',
      subject: '',
      vulnerabilityDiversity: '',
      vulnerabilityDiversityDetail: '',
      warrantReferenceNumber: '',
    })
  })

  it('uses unsaved values if there is one error value but no API values', () => {
    const formValues = getFormValues({
      errors: { lastReleaseDate: errors.lastReleaseDate },
      unsavedValues,
      apiValues: {} as DecoratedRecall,
    })
    expect(formValues).toEqual({
      confirmedRecallType: 'NO',
      arrestIssues: 'YES',
      arrestIssuesDetail: 'Detail..',
      authorisingAssistantChiefOfficer: 'Carrie Grant',
      bookingNumber: '87378435D',
      conditionalReleaseDateParts: {
        day: '05',
        month: '12',
        year: '2020',
      },
      confirmDossierEmailSent: 'YES',
      confirmRecallNotificationEmailSent: 'YES',
      contraband: 'YES',
      contrabandDetail: 'Likelihood of smuggling knives',
      currentPrison: 'ACL',
      details: 'Detail for note...',
      dossierEmailSentDateParts: {
        day: '17',
        month: '11',
        year: '2020',
      },
      hasDossierBeenChecked: 'YES',
      inCustodyAtBooking: 'NO',
      inCustodyAtAssessment: 'YES',
      indexOffence: 'Assault',
      lastReleaseDateParts: {
        day: 'ee',
        month: 'rr',
        year: 'www',
      },
      lastReleasePrison: 'Portland',
      legalRepresentativeInfo_email: 'jenny@edwards.com',
      legalRepresentativeInfo_fullName: 'Jenny Edwards',
      legalRepresentativeInfo_phoneNumber: '07484839483',
      licenceConditionsBreached: '(iii) three \n (iv) four',
      licenceExpiryDateParts: {
        day: '05',
        month: '12',
        year: '2020',
      },
      localPoliceForceId: 'dyfed-powys',
      mappaLevel: 'LEVEL_2',
      missingDocumentsDetail: 'Detail..',
      partBDetails: 'Part B detail',
      partBReceivedDateParts: {
        values: {
          day: '13',
          month: '',
          year: '2016',
        },
      },
      previousConvictionMainName: 'Wayne Holt',
      previousConvictionMainNameCategory: 'FIRST_LAST',
      licenceNameCategory: 'FIRST_LAST',
      localDeliveryUnit: 'ISLE_OF_MAN',
      probationOfficerEmail: 'andy@probation.gov.uk',
      probationOfficerName: 'Andy Fleming',
      probationOfficerPhoneNumber: '0739738383',
      reasonsForRecall: ['POOR_BEHAVIOUR_NON_COMPLIANCE'],
      recallEmailReceivedDateTimeParts: {
        day: '05',
        hour: '15',
        minute: '33',
        month: '12',
        year: '2020',
      },
      recallNotificationEmailSentDateTimeParts: {
        day: '23',
        hour: '6',
        minute: '34',
        month: '04',
        year: '2019',
      },
      recommendedRecallType: 'STANDARD',
      rereleaseSupported: 'NO',
      rescindRequestDetail: 'Detail...',
      rescindRequestEmailReceivedDateParts: {
        day: '23',
        hour: '6',
        minute: '34',
        month: '04',
        year: '2019',
      },
      returnedToCustodyDateTimeParts: {
        values: {
          day: '05',
          hour: '05',
          minute: '3',
          month: '12',
          year: '2021',
        },
      },
      returnedToCustodyNotificationDateTimeParts: {
        values: {
          day: '05',
          hour: '05',
          minute: '2',
          month: '12',
          year: '2021',
        },
      },
      seniorProbationOfficerInfo_email: 'jim@probation.com',
      seniorProbationOfficerInfo_fullName: 'Jimi Matthews',
      seniorProbationOfficerInfo_phoneNumber: '07434534583',
      seniorProbationOfficerInfo_functionalEmail: 'unsaved@probation.com',
      sentenceDateParts: {
        day: '05',
        month: '12',
        year: '2020',
      },
      sentenceExpiryDateParts: {
        day: '05',
        month: '12',
        year: '2020',
      },
      sentenceLengthParts: {
        days: '',
        months: '3',
        years: '',
      },
      sentencingCourt: 'Dorchester',
      subject: 'Subject for note',
      vulnerabilityDiversity: 'NO',
      warrantReferenceNumber: '02RC/1234567C12345',
    })
  })

  it('uses all error values over unsaved values', () => {
    const formValues = getFormValues({ errors, unsavedValues, apiValues: {} as DecoratedRecall })
    expect(formValues).toEqual({
      confirmedRecallType: '',
      arrestIssues: '',
      arrestIssuesDetail: '',
      authorisingAssistantChiefOfficer: '',
      bookingNumber: '',
      conditionalReleaseDateParts: {
        day: '05',
        month: '12',
        year: '',
      },
      confirmDossierEmailSent: '',
      confirmRecallNotificationEmailSent: '',
      contraband: '',
      contrabandDetail: '',
      currentPrison: '',
      details: '',
      dossierEmailSentDateParts: {
        day: '13',
        month: '',
        year: '2016',
      },
      hasDossierBeenChecked: '',
      previousConvictionMainNameCategory: '',
      licenceNameCategory: '',
      inCustodyAtBooking: '',
      inCustodyAtAssessment: '',
      indexOffence: '',
      lastReleaseDateParts: {
        day: 'ee',
        month: 'rr',
        year: 'www',
      },
      lastReleasePrison: '',
      legalRepresentativeInfo_email: 'invalidemail.com',
      legalRepresentativeInfo_fullName: '',
      legalRepresentativeInfo_phoneNumber: '999',
      licenceConditionsBreached: '',
      licenceExpiryDateParts: {
        day: '05',
        month: '',
        year: '',
      },
      localPoliceForceId: '',
      mappaLevel: '',
      missingDocumentsDetail: '',
      partBDetails: '',
      partBReceivedDateParts: {
        values: {
          day: '13',
          month: '',
          year: '2016',
        },
      },
      previousConvictionMainName: '',
      localDeliveryUnit: '',
      probationOfficerEmail: 'invalid@email',
      probationOfficerName: '',
      probationOfficerPhoneNumber: '999',
      reasonsForRecall: '',
      reasonsForRecallOtherDetail: '',
      recallEmailReceivedDateTimeParts: {
        day: '05',
        hour: '15',
        minute: '33',
        month: '12',
        year: '',
      },
      recallNotificationEmailSentDateTimeParts: {
        day: '05',
        hour: '05',
        minute: '3',
        month: '',
        year: '',
      },
      recommendedRecallType: '',
      rereleaseSupported: '',
      rescindRequestDetail: '',
      rescindRequestEmailReceivedDateParts: {
        day: '',
        month: '43',
        year: '',
      },
      returnedToCustodyDateTimeParts: {
        day: '05',
        hour: '05',
        minute: '3',
        month: '',
        year: '',
      },
      returnedToCustodyNotificationDateTimeParts: {
        day: '05',
        hour: '05',
        minute: '3',
        month: '',
        year: '',
      },
      seniorProbationOfficerInfo_email: 'invalidemail.com',
      seniorProbationOfficerInfo_fullName: '',
      seniorProbationOfficerInfo_phoneNumber: '999',
      seniorProbationOfficerInfo_functionalEmail: '',
      sentenceDateParts: {
        day: '05',
        month: '',
        year: '2020',
      },
      sentenceExpiryDateParts: {
        day: '',
        month: '',
        year: '',
      },
      sentenceLengthParts: {
        days: '',
        months: 'rr',
        years: '',
      },
      sentencingCourt: '',
      subject: '',
      vulnerabilityDiversity: '',
      vulnerabilityDiversityDetail: '',
      warrantReferenceNumber: '',
    })
  })

  it('uses API values in addition to the one error value, if no unsaved values', () => {
    const formValues = getFormValues({
      errors: { lastReleaseDate: errors.lastReleaseDate },
      unsavedValues: {},
      apiValues: apiValues as DecoratedRecall,
    })
    expect(formValues).toEqual({
      additionalLicenceConditions: 'YES',
      additionalLicenceConditionsDetail: 'one, two',
      confirmedRecallType: 'FIXED',
      confirmedRecallTypeDetailFixed: 'Agree with fixed term recall recommendation',
      arrestIssues: 'YES',
      arrestIssuesDetail: 'Detail...',
      authorisingAssistantChiefOfficer: 'Bob Monkfish',
      bookingNumber: 'A123456',
      conditionalReleaseDateParts: {
        day: '03',
        month: '12',
        year: '2021',
      },
      contraband: 'YES',
      contrabandDetail: 'Intention to smuggle drugs',
      currentPrison: 'KTI',
      differentNomsNumber: 'YES',
      differentNomsNumberDetail: 'AC3408303',
      dossierEmailSentDateParts: {
        day: '08',
        month: '09',
        year: '2021',
      },
      hasDossierBeenChecked: 'YES',
      inCustodyAtBooking: 'NO',
      inCustodyAtAssessment: 'YES',
      previousConvictionMainNameCategory: 'OTHER',
      legalRepresentativeInfo_email: 'jenny@legalreps.com',
      legalRepresentativeInfo_fullName: 'Jenny Eclair',
      legalRepresentativeInfo_phoneNumber: '07824637629',
      licenceNameCategory: 'FIRST_LAST',
      indexOffence: 'Burglary',
      lastKnownAddressOption: 'YES',
      lastReleaseDateParts: {
        day: 'ee',
        month: 'rr',
        year: 'www',
      },
      lastReleasePrison: 'KTI',
      licenceConditionsBreached: '(i) one (ii) two',
      licenceExpiryDateParts: {
        day: '03',
        month: '08',
        year: '2021',
      },
      localPoliceForceId: 'devon-and-cornwall',
      mappaLevel: 'LEVEL_1',
      previousConvictionMainName: 'Walter Holt',
      localDeliveryUnit: 'CENTRAL_AUDIT_TEAM',
      probationOfficerEmail: 'probation.office@justice.com',
      probationOfficerName: 'Dave Angel',
      probationOfficerPhoneNumber: '07473739388',
      reasonsForRecall: ['OTHER', 'ELM_FAILURE_CHARGE_BATTERY'],
      reasonsForRecallOtherDetail: 'other reason detail...',
      recallEmailReceivedDateTimeParts: {
        day: '05',
        hour: '15',
        minute: '33',
        month: '12',
        year: '2020',
      },
      recallNotificationEmailSentDateTimeParts: {
        day: '15',
        hour: '14',
        minute: '04',
        month: '08',
        year: '2021',
      },
      recommendedRecallType: 'FIXED',
      rereleaseSupported: 'YES',
      returnedToCustodyDateTimeParts: {
        day: '22',
        hour: '13',
        minute: '45',
        month: '01',
        year: '2022',
      },
      returnedToCustodyNotificationDateTimeParts: {
        day: '23',
        hour: '08',
        minute: '22',
        month: '01',
        year: '2022',
      },
      seniorProbationOfficerInfo_email: 'mark@probation.com',
      seniorProbationOfficerInfo_fullName: 'Mark Harvard',
      seniorProbationOfficerInfo_phoneNumber: '07383789332',
      seniorProbationOfficerInfo_functionalEmail: 'general@probation.com',
      sentenceDateParts: {
        day: '03',
        month: '08',
        year: '2019',
      },
      sentenceExpiryDateParts: {
        day: '03',
        month: '02',
        year: '2021',
      },
      sentenceLengthParts: {
        days: 0,
        months: 3,
        years: 2,
      },
      sentencingCourt: 'ABDRCT',
      vulnerabilityDiversity: 'YES',
      vulnerabilityDiversityDetail: 'Various...',
      warrantReferenceNumber: '02RC/1234567C12345',
    })
  })

  it('uses all API values if no error or unsaved values', () => {
    const formValues = getFormValues({
      errors: {},
      unsavedValues: {},
      apiValues: {
        ...(apiValues as DecoratedRecall),
        confirmedRecallType: ConfirmedRecallTypeRequest.confirmedRecallType.STANDARD,
        confirmedRecallTypeDetail: 'Upgrade to standard recall recommendation',
      },
    })
    expect(formValues).toEqual({
      additionalLicenceConditions: 'YES',
      additionalLicenceConditionsDetail: 'one, two',
      confirmedRecallType: 'STANDARD',
      confirmedRecallTypeDetailStandard: 'Upgrade to standard recall recommendation',
      arrestIssues: 'YES',
      arrestIssuesDetail: 'Detail...',
      authorisingAssistantChiefOfficer: 'Bob Monkfish',
      bookingNumber: 'A123456',
      conditionalReleaseDateParts: {
        day: '03',
        month: '12',
        year: '2021',
      },
      contraband: 'YES',
      contrabandDetail: 'Intention to smuggle drugs',
      currentPrison: 'KTI',
      differentNomsNumber: 'YES',
      differentNomsNumberDetail: 'AC3408303',
      dossierEmailSentDateParts: {
        day: '08',
        month: '09',
        year: '2021',
      },
      hasDossierBeenChecked: 'YES',
      previousConvictionMainNameCategory: 'OTHER',
      licenceNameCategory: 'FIRST_LAST',
      inCustodyAtBooking: 'NO',
      inCustodyAtAssessment: 'YES',
      indexOffence: 'Burglary',
      lastKnownAddressOption: 'YES',
      lastReleaseDateParts: {
        day: '03',
        month: '08',
        year: '2020',
      },
      lastReleasePrison: 'KTI',
      legalRepresentativeInfo_email: 'jenny@legalreps.com',
      legalRepresentativeInfo_fullName: 'Jenny Eclair',
      legalRepresentativeInfo_phoneNumber: '07824637629',
      licenceConditionsBreached: '(i) one (ii) two',
      licenceExpiryDateParts: {
        day: '03',
        month: '08',
        year: '2021',
      },
      localPoliceForceId: 'devon-and-cornwall',
      mappaLevel: 'LEVEL_1',
      previousConvictionMainName: 'Walter Holt',
      localDeliveryUnit: 'CENTRAL_AUDIT_TEAM',
      probationOfficerEmail: 'probation.office@justice.com',
      probationOfficerName: 'Dave Angel',
      probationOfficerPhoneNumber: '07473739388',
      reasonsForRecall: ['OTHER', 'ELM_FAILURE_CHARGE_BATTERY'],
      reasonsForRecallOtherDetail: 'other reason detail...',
      recallEmailReceivedDateTimeParts: {
        day: '05',
        hour: '15',
        minute: '33',
        month: '12',
        year: '2020',
      },
      recallNotificationEmailSentDateTimeParts: {
        day: '15',
        hour: '14',
        minute: '04',
        month: '08',
        year: '2021',
      },
      recommendedRecallType: 'FIXED',
      rereleaseSupported: 'YES',
      returnedToCustodyDateTimeParts: {
        day: '22',
        hour: '13',
        minute: '45',
        month: '01',
        year: '2022',
      },
      returnedToCustodyNotificationDateTimeParts: {
        day: '23',
        hour: '08',
        minute: '22',
        month: '01',
        year: '2022',
      },
      seniorProbationOfficerInfo_email: 'mark@probation.com',
      seniorProbationOfficerInfo_fullName: 'Mark Harvard',
      seniorProbationOfficerInfo_phoneNumber: '07383789332',
      seniorProbationOfficerInfo_functionalEmail: 'general@probation.com',
      sentenceDateParts: {
        day: '03',
        month: '08',
        year: '2019',
      },
      sentenceExpiryDateParts: {
        day: '03',
        month: '02',
        year: '2021',
      },
      sentenceLengthParts: {
        days: 0,
        months: 3,
        years: 2,
      },
      sentencingCourt: 'ABDRCT',
      vulnerabilityDiversity: 'YES',
      vulnerabilityDiversityDetail: 'Various...',
      warrantReferenceNumber: '02RC/1234567C12345',
    })
  })

  it('sets values to undefined if none supplied', () => {
    const formValues = getFormValues({ errors: {}, unsavedValues: {}, apiValues: {} as DecoratedRecall })
    expect(formValues).toEqual({})
  })
})
