---
# Per environment values which override defaults in manage-recalls-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-recalls-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: ppud-replacement-preprod-cert
    # which cluster are we on: live-1 is blue, live is green
    contextColour: blue

  env:
    INGRESS_URL: "https://manage-recalls-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    MANAGE_RECALLS_API_URL: "https://manage-recalls-api-preprod.hmpps.service.justice.gov.uk"
    SENTRY_ENVIRONMENT: "PRE-PROD"

generic-prometheus-alerts:
  alertSeverity: ppud-replacement-preprod
  extraDashboardTags:
    - ppud-replacement
    - manage-recalls
    - pre-prod
