---
# Per environment values which override defaults in manage-recalls-ui/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: manage-recalls.hmpps.service.justice.gov.uk
    tlsSecretName: ppud-replacement-prod-cert
    # which cluster are we on: live-1 is blue, live is green
    contextColour: blue

  env:
    INGRESS_URL: "https://manage-recalls.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    MANAGE_RECALLS_API_URL: "https://manage-recalls-api.hmpps.service.justice.gov.uk"
    SENTRY_DSN: https://4eb36239d29c4114b9d90b810063261c@o345774.ingest.sentry.io/5939012
    SENTRY_ENVIRONMENT: "PROD"
    ENVIRONMENT: "PRODUCTION"

generic-prometheus-alerts:
  alertSeverity: ppud-replacement-prod
  extraDashboardTags:
    - ppud-replacement
    - manage-recalls
    - prod
