---
# Per environment values which override defaults in manage-recalls-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-recalls-dev.hmpps.service.justice.gov.uk
    tlsSecretName: ppud-replacement-dev-cert

  env:
    INGRESS_URL: "https://manage-recalls-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    MANAGE_RECALLS_API_URL: "https://manage-recalls-api-dev.hmpps.service.justice.gov.uk"
    SENTRY_ENV: "DEV"

generic-prometheus-alerts:
  alertSeverity: ppud-replacement-alerts
