---
# Per environment values which override defaults in manage-recalls-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-recalls-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: ppud-replacement-preprod-cert

  env:
    INGRESS_URL: "https://manage-recalls-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    MANAGE_RECALLS_API_URL: "https://manage-recalls-api-preprod.hmpps.service.justice.gov.uk"
    SENTRY_DSN: https://4eb36239d29c4114b9d90b810063261c@o345774.ingest.sentry.io/5939012
    SENTRY_ENVIRONMENT: "PRE-PROD"
    ENVIRONMENT: "PRE-PRODUCTION"

generic-prometheus-alerts:
  alertSeverity: ppud-replacement-preprod
  extraDashboardTags:
    - ppud-replacement
    - manage-recalls
    - pre-prod
