---
# Per environment values which override defaults in manage-recalls-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-recalls-dev.hmpps.service.justice.gov.uk
    tlsSecretName: ppud-replacement-dev-cert
    # which cluster are we on: live-1 is blue, live is green
    contextColour: blue

  env:
    INGRESS_URL: "https://manage-recalls-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    MANAGE_RECALLS_API_URL: "https://manage-recalls-api-dev.hmpps.service.justice.gov.uk"
    SENTRY_DSN: "DO_NOT_TRACK"
    SENTRY_ENVIRONMENT: "DEV"
    ENVIRONMENT: "DEVELOPMENT"

generic-prometheus-alerts:
  alertSeverity: ppud-replacement-alerts
  extraDashboardTags:
    - ppud-replacement
    - manage-recalls
    - dev
