---
# Per environment values which override defaults in manage-recalls-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-recalls-new.hmpps.service.justice.gov.uk
    tlsSecretName: manage-recalls-cert

  env:
    INGRESS_URL: "https://manage-recalls-new.hmpps.service.justice.gov.uk"

generic-prometheus-alerts:
  extraDashboardTags:
    - manage-recalls
    - prod
